### ISSUE TITLE
Entity search should not show deprecated/retired entities first

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#105]
When searching for an entity, the entity search should not display the retired/deprecated entities first:

![Image](https://github.com/user-attachments/assets/0d381880-d2bc-48dc-b93e-14d14f6398d5)

**Comment by matthewhorridge** [comment]
This can be filtered out in the form configuration.  Add an extra criteria for "Is Not Deprecated".  (Went through this in stand up)
