### ISSUE TITLE
Improvements to Postcoordination UI

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#113]
- [ ] adjust the effective width of all three icons ("allowed", "required" and "not allowed") to be the same, e.g. 14px, even if they icon's size is left 20x20 icon. Reason: The current "not allowed" icon is too wide, which makes the table with lots of "not allowed" values look crowded, and tables with various selections look unharmonious
- [x]  Set the vertical alignment of the linearization names in the post-coordination table to center. The top alignment looks strange, especially for the non-telescopic ("root") linearizations
- [x] The telescopic linearization should be marked with the nice "sub-element" arrow icon also in the last (right-most) column of the table, not just the first one, if possible
- [x] Reduce the top and bottom padding in the custom scale value table header. Please make sure that the table is always Open when the post-coordination axes is selected.

**Comment by csnyulas** [comment]
See also some related issues, such as #116 and #117

**Comment by soimugeoWB** [comment]
separate issue https://github.com/who-icatx/webprotege-postcoordination-service/issues/54 has been created for the first bullet point.
