### ISSUE TITLE
"Default" value for telescopic linearization in the Postcoordination table is not shown while cycling through values 

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#114]
While cycling through the possible values in the Postcoordination table for a given post-coordination axis in case of a telescopic linearization, I observed that the "Default" value, which is inherited from the "root" linearization, is not shown properly, but it is always shown as "not allowed", even when the root linearization is set to "Allowed" or "Required".

**Comment by csnyulas** [comment]
This seems to have been fixed now. @alexsilaghi if you are happy with the implementation of the fix, feel free to close this issue.

**Comment by alexsilaghi** [comment]
done
