### ISSUE TITLE
Post-Coordination Value Set editing card views should always be presented in a fixed order

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#117]
If we edit the content of the Post-Coordination table that had already some post-coordination axes selected, and we check a new post-coordination access, the card view for the editing of the related value set for the newly selected post-coordination axes will appear at the bottom of the list. Only after saving the changes, and reloading the content of the Post-Coordination view, will the cards be ordered "properly", i.e. in the order they are specified as columns in the PC table.

**Steps to reproduce:**
- Select an entity in the "Postcoordinations" tab that has the "Severity" and "Time in Life" axes selected 
- Start editing of the post-coordination content, by pressing on the "Edit values" button
- Select the "Course" post-coordination axes as allowed or required for one of the linearizations

**Observe** that the Value Set editing card for the "Course" axis appears at the bottom of the card list (after the card for the "Time in Life" axis)
**Expected behavior:**  The Value Set editing card for the "Course" axis should appear after the "Severity" and before "Time in Life", as this is the order of the columns in the table, and this is the "logical order" that makes sense for the users.

**Comment by soimugeoWB** [comment]
Thank you for the detailed issue! Steps to reproduce and actual/expected outcome helped a lot!
