### ISSUE TITLE
Backreference from JSON to the ontology

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#13]
We need to decide how we want to link the operational knowledge (JSON) to the ontology entities it applies to.

One suggestion is to use a property/key in JSON that contains the ontology URI of the entity. We need a good name for this JSON property. @csnyulas suggested "appliesTo", so that it is generic, and it can be used for other use cases. Other suggestions are: "referenceEntityId", feel free to suggest others in the comments.

Also, do we need the forward reference (from the ontology to a JSON record). I guess not, and it would only complicate things.

**Comment by matthewhorridge** [comment]
Doesn't it just apply to the entity regardless of the ontology?  I suggest we use the notation that already exists in WebProtege if so.

**Comment by csnyulas** [comment]
I am closing this as we decided to use the `whoficEntityIri` property for this purpose, which can be found in various files (LinkML models and sample JSON files) in the `whofic-models` project:
https://github.com/search?q=repo%3Awho-icatx/whofic-models%20%22whoficEntityIri%22&type=code
