### ISSUE TITLE
Term instances should have UUIDs as identifiers

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#146]
When creating a new term instance (e.g., title term, base index term, etc.), the IRI of the term, should have a base URI:

`http://id.who.int/icd/`

followed by a UUID.

e.g.:
`http://id.who.int/icd/d8b67380-ca29-47a2-90e7-969a28baf516`

The term instances should not have their ID generated from the label (as it is now, e.g., `http://who.int/icd#TitleTerm_API-created_entity_through_Postman`), and should not use the ID server that will be used for generating IDs for entities.

**Comment by soimugeoWB** [comment]
this is fixed and deployed to ashybush.
![image](https://github.com/user-attachments/assets/061918b6-3eef-4573-9a02-04d609457601)
