### ISSUE TITLE
Create a mechanism to read the released classes

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#17]
The classes that have already been released in a WHO-FIC release are restricted in terms of what operations can be applied to them (E.g. hierarchy changes)

We need a mechanism through which iCAT-X reads the lists of released classes at init, and then marks them, so that the info can be used for checking different operations.

Current iCAT:
- it reads a file from a set location with the id of classes that are released. It may also add a boolean flag on them that they were released. This happens once at release.

- Released classes should be marked in the class tree with a blue full circle icon, as in current iCAT.

**Comment by csnyulas** [comment]
The original iCAT code has a full solution implemented to deal with the reading, caching and displaying of the "isReleased" status of an entity (e.g. class). Feel free to get inspiration from and/or reuse relevant parts of the old code. Here is a starting point that you can use for exploring related code in the old code base: https://github.com/tudorache/icat/commit/08cb2dfb82782a4cd767b05aca97d856a3b2af4e
