### ISSUE TITLE
Integrate the ICD-API search in the iCAT-X class tree

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#2]
The ICD-API search function is tailored for ICD users, and should be integrated in the iCAT-X class tree, similarly to how it is integrated in the current iCAT.  It should allow searching for classes in different subtrees, and the selection of a search result in the iCAT class tree.

The ICD-API Search UI component will be provided by the ICD Embedded Browser: https://icd.who.int/docs/icd-api/icd11ect-1.7/EmbeddedBrowser/

Playground for the Embedded Browser: https://codepen.io/mdonada/pen/mdgEWQx

**Comment by matthewhorridge** [comment]
Quick update:  This is nominally complete.  Just waiting for a code review from me.
