### ISSUE TITLE
[ActionExecutionException] Internal Server Error(500) when uploading a small ontology

### ISSUE THREAD

**Issue by samsontu** [who-icatx/icatx-project#23]
I tried to upload a small ontology (72.3 KB) to the locally-deployed webprotege, either while creating a new project or updating an existing project. Each time I got "[ActionExecutionException] Internal Server Error(500)" and then "Internal Server Error(500)" messages.

**Comment by matthewhorridge** [comment]
Quick update.  I've been working on this over the last couple of days.  Should push a fix soon @samsontu.

**Comment by matthewhorridge** [comment]
Fixed some time ago.
