### ISSUE TITLE
[FORMS]: Serialization error when trying to save a form with formField with formType single choice -> widget type combo box

### ISSUE THREAD

**Issue by soimugeoWB** [who-icatx/icatx-project#26]
- serialization error for formField -> FormType single choice -> widget type combo box. whole project can no longer properly display forms from this point on.

Steps to reproduce:
1. Create new project.
2. Add a few classes a,b,c,d.
3.  add relationshipProperty isObsolete.
4. go to form.
5. Add FormA with language en.
6. go to Form details.
7. Add form field "Form fieldA"
8. put binding -> Relationship property: isObsolete -> Relationship value filter: has any value -> Field type: single choice -> Widget type: Combo box -> Choice Fixed.
9. click on + unde Choices -> value: true -> value label: Yes -> language: en
10. click on + unde Choices -> value: false -> value label: No -> language: en
11. form activation -> form purpose: entity viewing/editing -> entity criteria: is a subclas of: c
12. hit apply.

Expected outcome:
Form is saved and you click ok to leave forms page.

Actual outcome:
Serialization error is seen and if there were any forms previously you can no longer see them in the forms page.

![image](https://github.com/who-icatx/icatx-project/assets/149394944/4da35029-bca4-4644-a11d-ed6bed39c715)

**Comment by matthewhorridge** [comment]
This is working now.  Tested with webprotege-backend-service `1.2.2`, webprotege-gwt-ui `5.0.6`
