### ISSUE TITLE
Share settings are not saved

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#28]
Make some sharing settings from the Share menu, click Apply, go back to Sharing menu, and all the settings are gone (although I think they are saved and used, but nothing is shown)

**Comment by soimugeoWB** [comment]
need to fix this before continuing with https://github.com/who-icatx/icatx-project/issues/46

**Comment by soimugeoWB** [comment]
i will merge the chances for this together with the changes for https://github.com/who-icatx/icatx-project/issues/46
