### ISSUE TITLE
Implement a widget for class creation that checks for duplicates

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#4]
When a new class is created in iCAT-X, the id/name of the class should be retrieved from a WHO name server. The id is the IRI of the class in OWL.

If the WHO name server is not available, we need to create a temporary id, which should be later replaced by the real id. This may cause some issues with the change tracking.

Also, the widget for class creation should have a search integrated to prevent the creation of duplicate classes. The widget should also require to enter a reason for change.

Example from current iCAT:
<img width="498" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/23872881-6aaa-46db-9d10-8649f5956599">

**Comment by tudorache** [comment]
Check if the name server is necessary, if we could generate the IRI instead by some rules

**Comment by tudorache** [comment]
After consulting with Can, we can generate the IRI from iCAT, not necessarily through the name server. We need to make sure that the generated IRIs have not been used before.

Another related id issue: we need to maintain the IDs for the migrated terms (e.g. title, syns, etc.), as they are essential for translation and other functionalities.

**Comment by samsontu** [comment]
Terms such as titles and synonyms have IDs that need to be maintained? That means we can't treat them as strings as they are in the whofic-date.owl file, and we can't use the OWL export as the starting point for the iCAT-X Foundation representation.

**Comment by tudorache** [comment]
We can extend the script to export the current term id-s as well. If needed, we can represent the terms as reified instances, although I would rather not.

**Comment by tudorache** [comment]
We need to configure the id generation in iCAT for newly created entities. See here #12

**Comment by tudorache** [comment]
More requirements:
- Only one class should be created at once. The search should search for the label of that class. Ideally this should be a project configuration (create one vs. multiple classes at once)
- We should record the reason for change as a note attached to the newly created class
- Language tag should not be shown. Ideally, this should also be configurable.

**Comment by csnyulas** [comment]
As per discussion in project meeting from 5/8/2028, although language tags should not be shown (see requirements in previous comment), the language tag of the title of the class should be set to the default language of the project (which should be set to to English `en`).
