### ISSUE TITLE
Configuring a form with a property that has two enumerated values results in JSON Deserialization Error that removes all previously configured forms.

### ISSUE THREAD

**Issue by samsontu** [who-icatx/icatx-project#40]
To reproduce the problem, on the WHO azure WebProtege server,
1. Go to ICD Parasitic+ICF Mental+ICHI TargetMental v3 ontology
2. Create a form with the field with baseIndex annotation property binding
3. Specify Grid field type, subject type Individual, subject type BaseIndexTerm
4. Create column with indexType binding
5. Specify field type single choice, radio button (or combo box)
6. Fixed values IndexType.Synonym and IndexType.Narrower
7. Apply the form configuration
You should get a JSON Deserialization Error

**Comment by matthewhorridge** [comment]
This is working now.  Tested with webprotege-backend-service `2.5.3`, webprotege-gwt-ui `6.0.1`, webprotege-forms `1.1.9`
