### ISSUE TITLE
Create class does not add the "en" language tag to the icd:label of the title instance

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#57]
Create a class on ashybush in WHOFIC Foundation. It will create the correct title instance of LanguageTerm, and it adds to the title instance the icd:label with the title text, but it does not add the language tag "en", so the title will not be shown in the form of the class.

Here is the history for the create action that shows that the "en" tag is not added:
<img width="568" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/785fe1f8-1bc7-4ad9-bae5-0a6821e88de2">

For the line:
<img width="472" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/89dfe484-f868-4b90-9822-7edee4840a29">

it should show for the value ... "Test 234"@en

**Comment by soimugeoWB** [comment]
When it creates the label it will set the language tag that is set on the project. Do we have a language tag set on the project here?
![image](https://github.com/who-icatx/icatx-project/assets/149394944/69594f66-0d5d-4446-9ab3-493423dddccd)

**Comment by soimugeoWB** [comment]
language tag needs to be set here 
![image](https://github.com/who-icatx/icatx-project/assets/149394944/96702886-fc8d-4b29-91f9-a0ac40b3a10e)
