### ISSUE TITLE
Cannot add a boolean value of true as a fixed value for a field

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#64]
On ashybush, in WHOFIC Foundation, look in the Forms, Title and Definition, Field no. 5

property isObsolete, which has as range boolean.

I tried to set as value "true", or "xsd:true" as a fixed value for multiple choice, but it is created as a plain literal, not as a boolean.

We need to be able to set also boolean values.

The range of isObsolete is xsd:boolean, the form could figure out from the range which type of value it should create.

<img width="148" alt="image" src="https://github.com/who-icatx/icatx-project/assets/2709502/2e4677d6-a243-45ed-a0b5-da18b2c1d4be">

**Comment by matthewhorridge** [comment]
Work around type TRUE instead of true (I think)

**Comment by matthewhorridge** [comment]
This is fixed now.  To be merged into main.
