### ISSUE TITLE
Support retirement of classes

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#7]
To support retiring, iCAT-X needs to be aware of the entities that are part of an official WHO-FIC release, so that it can prevent their retirement. We will discuss with the WHO team the best way on how to represent released entities. One possibility is to use a Boolean flag that will be represented as an annotation property on an entity. This annotation property will have the Boolean value true, if the entity was already released. 

The retirement operation will work with the release representation to check if the retirement is allowed. If the operation is allowed, the editor will ask the user if existing subclasses should also be retired (that have not been released already). Once the user confirms the retirement operation, we will mark the retired entities using the owl:deprecated annotation property. The retired entities will be moved to a retired tree, and they will be hidden from view (by default). However, the editor can be configured to show the retired entities as well. Using the standard OWL deprecation mechanism will ensure better interoperation with other ontologies and terminologies, as well as other OWL-based tools.

We will discuss with WHO team, which information from pre-retirement of an entity should be kept, for example, the parents of an entity, which can be used to automate the unretirement of that entity.

**Comment by tudorache** [comment]
Here is the current iCAT implementation for the retirement:
https://github.com/protegeproject/icat/blob/master/src/edu/stanford/bmir/protege/web/server/RetirementManager.java

- It creates a cache with the released classes (which cannot be retired) from a file stored at some predefined URL. If it cannot retrieve the file, it uses a locally cached file.
- It provides the methods to check if a class is in a retired tree (and hence retired)

Current implementation of retired classes in iCAT:
- Each top-level branch has two classes (sometimes only one of them): "to be retired" and "needing a decision".
- When a class needs to be retired, the users just moves the class in one of these two branches.

We can discuss if we want to keep this behavior also for iCAT-X, or, have one "Retired" branch, or some other solution.

- Released classes cannot be retired. So, they cannot be moved in a retired tree.

**Comment by csnyulas** [comment]
Notes from discussion with @cannn from May 16th, 2024 (extracted from Meeting Minutes)
**Retire operation**
- The retire operation in ICD happens by moving a class under a class starting with the “To be retired”, usually of the form “To be retired - <PARENT_CLASS>“
- There are different solutions that we can consider:
 1. Do not provide an explicit “Retire” functionality to the user. Let them manually execute the retirement operation, by changing the parents of the class with drag and drop or through the Change parents feature
 2. The “Retire” action would just provide generic instruction to the user about what they need to do to retire a class, i.e. that they should move the class under the subclass of the chapter class whose name starts with “To be retired“ (by removing all superclasses of this class and adding that class as its only superclass)
 3. The “Retire” action would provide instructions to the user about what they need to do to retire a class by saying the things mentioned in the previous option, but also providing the name of the class(es) (inventing one, if none exists already) that they should consider as the new superclass
 4. Provide the list of “To be retired” classes that could be the new superclasses of this class, and let the user choose under which one(s) they want this classed to be placed. After user selects and confirms, remove all the current superclasses and add the selected “To be retired…” class(es) as it superclass.
- For option 3 and 4 we need an algorithm that calculates all paths to root for a given class, identifies the chapter level classes and the appropriate “To be retired…” class under them. These can be cached for performance improvements, but in that case a cache updated mechanism needs to be set in place if new “To be retired…” classes are created/deleted (i.e. through a class creation/title change operation). Another solution would be to discover all sibling and “uncle” classes (i.e. siblings of parents and ancestors) that start with “To be retired”. In both cases we still need a mechanism to suggest the creation of a new “To be retired…” class, if none exists at the appropriate chapter level.
- The solution should be generic to work for ICF and ICHI Chapters, including Extension codes
