### ISSUE TITLE
Create new History view where to fetch linearization changes and project changes

### ISSUE THREAD

**Issue by soimugeoWB** [who-icatx/icatx-project#80]
Create new History view where to fetch linearization changes and project changes.

Here the changes will be mapped to a new object and if that object contains ontology changes then it will show a line for ontology changes as before, but if that object does not contain ontology changes then it is a linearization change and we will show a line with a new component for the linearization changes.

**Comment by csnyulas** [comment]
I assume that this is done, and resulted in the two views **iCAT-X Project History** and **iCAT-X-Entity Changes**, which were already included in Deliverable 3 (I also set that milestone for this issue). If you can confirm, please feel free to close this issue @soimugeoWB .
