### ISSUE TITLE
Linearization View: Unset Linearization parents can't be edited 

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#82]
It seems like unset Linearization parents, such as for the linearization ICD-O in case of [Certain other disorders of infectious origin](https://webprotege-gwt-ui-server.ashybush-2afce3eb.northeurope.azurecontainerapps.io/webprotege/#projects/61f24481-8df3-4591-8a9c-a49702a33a21/perspectives/82003385-1817-49c2-a4b0-88e9e3b2d8ed?selection=Class(%3Chttp://id.who.int/icd/entity/1760597414%3E)) can't be edited. Why? 

![image](https://github.com/user-attachments/assets/571649f8-dbe2-43a1-bb0b-97f3651f550b)

**Comment by csnyulas** [comment]
Same problem even for the MMS linearization [Septic dermatitis](https://webprotege-gwt-ui-server.ashybush-2afce3eb.northeurope.azurecontainerapps.io/webprotege/#projects/61f24481-8df3-4591-8a9c-a49702a33a21/perspectives/82003385-1817-49c2-a4b0-88e9e3b2d8ed?selection=Class(%3Chttp://id.who.int/icd/entity/531258563%3E))

![image](https://github.com/user-attachments/assets/fe3be73e-0415-44e4-b98a-36f1bdb734db)

**Comment by alexsilaghi** [comment]
done and deployed
