### ISSUE TITLE
Linearization View: Switching between entities will result in loss of unsaved changes

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#85]
When switching selection to a new entity (selecting a new class in the Class Hierarchy view), after having changed some values in the Class, but before having saved those changes explicitly, will result in the loss of those changes.

The expected behavior would be to ask the user to confirm what he or she would like to happen with the unsaved changes. Possible options could be:
 - save changes before switching
 - discard changes
 - continue editing of linearization information of previous selection

**Comment by alexsilaghi** [comment]
This should be mitigated in the task @matthewhorridge  does , the one with mixed forms/views.

**Comment by csnyulas** [comment]
Regarding the integration that @matthewhorridge is working on, ideally this behavior should be implemented there as well, i.e. to have three buttons for the above actions:  
- "Save changes" - for saving changes before switching entity selection
- "Discard changes" - for not saving changes before switching entity selection 
- "Continue editing" - for not saving changes and not switching to other entity (remaining on the previous selection)

Additionally, the dialog should NOT pop up if there was no local changes made by the user (despite having pressed the "Edit values" button), because that would easily result in data corruption (i.e. overriding with old data something that another user has changed in the meantime).

If these features are not already considered to be included in the new functionality, we should perhaps create separate issues for them.
