### ISSUE TITLE
Coding notes should be visible also in read-only mode

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#89]
If the user is not in Edit mode, there is no way to see the entire coding note. Nothing happens if the user clicks on the coding note.

A dialog should come up that shows the markdown, and is readonly.

**Comment by alexsilaghi** [comment]
done and deployed

**Comment by csnyulas** [comment]
Please consider to add some improvements to better convey the fact that the presentation of the "Coding Notes" is in read-only mode, when the "Edit values" button was previously not pressed. For example by 
- removing the "Cancel" button (i.e. keep only the "OK" button
- removing the blinking cursor

**Comment by alexsilaghi** [comment]
done and deployed
